#!/bin/bash

set -e

LISTENBRAINZ_API_URL="https://api.listenbrainz.org/1/submit-listens"

usage() {
    echo "Usage: $0 [-h] [-d payloads_dir]"
    echo "  -h  Display help"
    echo "  -d  Path to payloads_dir generated by map_spotify_data.sh"
    echo "  -t  MusicBrainz token"
    exit 1
}

while getopts ":h:d:t:" opt; do
    case ${opt} in
    h)
        usage
        ;;
    d)
        PAYLOADS_DIR=$OPTARG
        ;;
    t)
        LISTENBRAINZ_TOKEN=$OPTARG
        ;;
    \?)
        echo "Invalid option: $OPTARG" 1>&2
        usage
        ;;
    :)
        echo "Invalid option: $OPTARG requires an argument" 1>&2
        usage
        ;;
    esac
done

if [ ! -d "$PAYLOADS_DIR" ]; then
    echo "Directory \"$PAYLOADS_DIR\" does not exist."
    usage
fi

if [ -z "$LISTENBRAINZ_TOKEN" ]; then
    echo "Please set the LISTENBRAINZ_TOKEN environment variable."
    usage
fi

mkdir -p "$PAYLOADS_DIR"/sent

for file in "$PAYLOADS_DIR"/payload_*.json; do
    echo "Sending $file..."
    curl -X POST \
        -H "Authorization: token $LISTENBRAINZ_TOKEN" \
        -H "Content-Type: application/json" \
        --fail-with-body \
        --data @"$file" \
        "$LISTENBRAINZ_API_URL"

    mv "$file" "$PAYLOADS_DIR"/sent/

    # To avoid rate limiting
    sleep 5
done

echo "Done!"
